language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

services:
  - elasticsearch

install:
  - pip install mongo-orchestration
  - sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-mapper-attachments/2.4.3

before_script:
  - sudo service elasticsearch restart
  - mongo-orchestration start
  - sleep 10
  - sudo lsof -n -iTCP:9200
  - sudo lsof -n -iTCP:8889

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
  - sudo service elasticsearch stop
